name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    # - name: Build Docker Image
    #   run: |
    #     docker build -t tariksaid/dualiza:latest .
        
    # - name: Push Docker Image
    #   run: |
    #     docker push tariksaid/dualiza:latest

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          # docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          # docker pull tariksaid/dualiza:latest
          # docker-compose up -d
          
